# Ceres 2.1.0 sources compiled into pimax_slam. third_party/ceres-solver is the pristine 2.1.0 submodule;
# the files Pimax patched are compiled from third_party/ceres-pimax instead (see its PIMAX_PATCH.md).
# Excluded from upstream: tests/benchmarks/gmock, the OpenMP and no-threads parallel_for back ends.
set(CERES_UPSTREAM_SOURCES
    internal/ceres/accelerate_sparse.cc
    internal/ceres/array_utils.cc
    internal/ceres/block_evaluate_preparer.cc
    internal/ceres/block_jacobian_writer.cc
    internal/ceres/block_jacobi_preconditioner.cc
    internal/ceres/block_random_access_dense_matrix.cc
    internal/ceres/block_random_access_diagonal_matrix.cc
    internal/ceres/block_random_access_matrix.cc
    internal/ceres/block_random_access_sparse_matrix.cc
    internal/ceres/block_structure.cc
    internal/ceres/canonical_views_clustering.cc
    internal/ceres/c_api.cc
    internal/ceres/cgnr_solver.cc
    internal/ceres/compressed_col_sparse_matrix_utils.cc
    internal/ceres/compressed_row_jacobian_writer.cc
    internal/ceres/compressed_row_sparse_matrix.cc
    internal/ceres/conditioned_cost_function.cc
    internal/ceres/conjugate_gradients_solver.cc
    internal/ceres/context.cc
    internal/ceres/context_impl.cc
    internal/ceres/coordinate_descent_minimizer.cc
    internal/ceres/corrector.cc
    internal/ceres/cost_function.cc
    internal/ceres/covariance.cc
    internal/ceres/covariance_impl.cc
    internal/ceres/cxsparse.cc
    internal/ceres/dense_cholesky.cc
    internal/ceres/dense_normal_cholesky_solver.cc
    internal/ceres/dense_qr.cc
    internal/ceres/dense_qr_solver.cc
    internal/ceres/dense_sparse_matrix.cc
    internal/ceres/dogleg_strategy.cc
    internal/ceres/dynamic_compressed_row_jacobian_writer.cc
    internal/ceres/dynamic_compressed_row_sparse_matrix.cc
    internal/ceres/dynamic_sparse_normal_cholesky_solver.cc
    internal/ceres/eigensparse.cc
    internal/ceres/evaluation_callback.cc
    internal/ceres/evaluator.cc
    internal/ceres/file.cc
    internal/ceres/first_order_function.cc
    internal/ceres/float_cxsparse.cc
    internal/ceres/float_suitesparse.cc
    internal/ceres/function_sample.cc
    internal/ceres/gradient_checker.cc
    internal/ceres/gradient_checking_cost_function.cc
    internal/ceres/gradient_problem.cc
    internal/ceres/gradient_problem_solver.cc
    internal/ceres/implicit_schur_complement.cc
    internal/ceres/inner_product_computer.cc
    internal/ceres/is_close.cc
    internal/ceres/iteration_callback.cc
    internal/ceres/iterative_refiner.cc
    internal/ceres/iterative_schur_complement_solver.cc
    internal/ceres/levenberg_marquardt_strategy.cc
    internal/ceres/linear_least_squares_problems.cc
    internal/ceres/linear_operator.cc
    internal/ceres/linear_solver.cc
    internal/ceres/line_search.cc
    internal/ceres/line_search_direction.cc
    internal/ceres/line_search_minimizer.cc
    internal/ceres/line_search_preprocessor.cc
    internal/ceres/local_parameterization.cc
    internal/ceres/loss_function.cc
    internal/ceres/low_rank_inverse_hessian.cc
    internal/ceres/manifold.cc
    internal/ceres/minimizer.cc
    internal/ceres/normal_prior.cc
    internal/ceres/parallel_for_cxx.cc
    internal/ceres/parallel_utils.cc
    internal/ceres/parameter_block_ordering.cc
    internal/ceres/partitioned_matrix_view.cc
    internal/ceres/polynomial.cc
    internal/ceres/preconditioner.cc
    internal/ceres/preprocessor.cc
    internal/ceres/problem.cc
    internal/ceres/problem_impl.cc
    internal/ceres/program.cc
    internal/ceres/reorder_program.cc
    internal/ceres/schur_complement_solver.cc
    internal/ceres/schur_jacobi_preconditioner.cc
    internal/ceres/schur_templates.cc
    internal/ceres/scratch_evaluate_preparer.cc
    internal/ceres/single_linkage_clustering.cc
    internal/ceres/solver.cc
    internal/ceres/solver_utils.cc
    internal/ceres/sparse_cholesky.cc
    internal/ceres/sparse_matrix.cc
    internal/ceres/sparse_normal_cholesky_solver.cc
    internal/ceres/stringprintf.cc
    internal/ceres/subset_preconditioner.cc
    internal/ceres/suitesparse.cc
    internal/ceres/thread_pool.cc
    internal/ceres/thread_token_provider.cc
    internal/ceres/triplet_sparse_matrix.cc
    internal/ceres/trust_region_preprocessor.cc
    internal/ceres/trust_region_step_evaluator.cc
    internal/ceres/trust_region_strategy.cc
    internal/ceres/types.cc
    internal/ceres/visibility_based_preconditioner.cc
    internal/ceres/visibility.cc
    internal/ceres/wall_time.cc
    internal/ceres/generated/partitioned_matrix_view_2_2_2.cc
    internal/ceres/generated/partitioned_matrix_view_2_2_3.cc
    internal/ceres/generated/partitioned_matrix_view_2_2_4.cc
    internal/ceres/generated/partitioned_matrix_view_2_2_d.cc
    internal/ceres/generated/partitioned_matrix_view_2_3_3.cc
    internal/ceres/generated/partitioned_matrix_view_2_3_4.cc
    internal/ceres/generated/partitioned_matrix_view_2_3_6.cc
    internal/ceres/generated/partitioned_matrix_view_2_3_9.cc
    internal/ceres/generated/partitioned_matrix_view_2_3_d.cc
    internal/ceres/generated/partitioned_matrix_view_2_4_3.cc
    internal/ceres/generated/partitioned_matrix_view_2_4_4.cc
    internal/ceres/generated/partitioned_matrix_view_2_4_6.cc
    internal/ceres/generated/partitioned_matrix_view_2_4_8.cc
    internal/ceres/generated/partitioned_matrix_view_2_4_9.cc
    internal/ceres/generated/partitioned_matrix_view_2_4_d.cc
    internal/ceres/generated/partitioned_matrix_view_2_d_d.cc
    internal/ceres/generated/partitioned_matrix_view_3_3_3.cc
    internal/ceres/generated/partitioned_matrix_view_4_4_2.cc
    internal/ceres/generated/partitioned_matrix_view_4_4_3.cc
    internal/ceres/generated/partitioned_matrix_view_4_4_4.cc
    internal/ceres/generated/partitioned_matrix_view_4_4_d.cc
    internal/ceres/generated/partitioned_matrix_view_d_d_d.cc
    internal/ceres/generated/schur_eliminator_2_2_2.cc
    internal/ceres/generated/schur_eliminator_2_2_3.cc
    internal/ceres/generated/schur_eliminator_2_2_4.cc
    internal/ceres/generated/schur_eliminator_2_2_d.cc
    internal/ceres/generated/schur_eliminator_2_3_3.cc
    internal/ceres/generated/schur_eliminator_2_3_4.cc
    internal/ceres/generated/schur_eliminator_2_3_6.cc
    internal/ceres/generated/schur_eliminator_2_3_9.cc
    internal/ceres/generated/schur_eliminator_2_3_d.cc
    internal/ceres/generated/schur_eliminator_2_4_3.cc
    internal/ceres/generated/schur_eliminator_2_4_4.cc
    internal/ceres/generated/schur_eliminator_2_4_6.cc
    internal/ceres/generated/schur_eliminator_2_4_8.cc
    internal/ceres/generated/schur_eliminator_2_4_9.cc
    internal/ceres/generated/schur_eliminator_2_4_d.cc
    internal/ceres/generated/schur_eliminator_2_d_d.cc
    internal/ceres/generated/schur_eliminator_3_3_3.cc
    internal/ceres/generated/schur_eliminator_4_4_2.cc
    internal/ceres/generated/schur_eliminator_4_4_3.cc
    internal/ceres/generated/schur_eliminator_4_4_4.cc
    internal/ceres/generated/schur_eliminator_4_4_d.cc
    internal/ceres/generated/schur_eliminator_d_d_d.cc
    internal/ceres/miniglog/glog/logging.cc)
set(CERES_PIMAX_SOURCES
    internal/ceres/block_sparse_matrix.cc
    internal/ceres/callbacks.cc
    internal/ceres/detect_structure.cc
    internal/ceres/residual_block.cc
    internal/ceres/residual_block_utils.cc
    internal/ceres/schur_eliminator.cc
    internal/ceres/trust_region_minimizer.cc
)
